# ==================================================
# NOTIFICATION SERVICE - LOCAL Environment
# ==================================================

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ccadb
spring.datasource.username=postgres
spring.datasource.password=root

# API Gateway URL
apigateway.service.url=http://localhost:7778

# Eureka URL
eureka.client.service-url.defaultZone=http://localhost:7777/eureka
